### ISSUE TITLE
charInfo_width dependency is no longer available

### ISSUE THREAD

**Issue by Khady** [ocaml-community/zed#42]
https://bitbucket.org/zandoye/charinfo_width/
https://opam.ocaml.org/packages/charInfo_width/

mercurial repos are no longer accessible on bitbucket. Which means this package can't be installed if the tarball isn't downloaded from opam's cache. Which isn't a good enough guaranty I would say.

[charinfo_width.1.1.0.tar.gz](https://github.com/ocaml-community/zed/files/5102352/charinfo_width.1.1.0.tar.gz)

**Comment by kandu** [comment]
Hi, @Khady!

Thanks for reporting this issue.
It's a known issue and had been fixed in PR https://github.com/ocaml/opam-repository/pull/17018

**Comment by Khady** [comment]
Ah sorry about that. I checked the opam website but not the GitHub repo. Thanks
